stages:
  download_zones:
    cmd:  curl 'https://api.electricitymap.org/v3/zones' > data/raw/electricitymaps_zones.json
    outs:
    - data/raw/electricitymaps_zones.json
  unpack_gridemissions:
    cmd: |
      tar xvfz data/raw/gridemissions_bulk_file.tar.gz -C data/interim/ && mv data/interim/processed data/interim/gridemissions
    outs:
    - data/interim/gridemissions
